CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    rental_price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE game_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_game_copies_game
        FOREIGN KEY (game_id)
        REFERENCES games (id)
);

CREATE TABLE rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    due_date DATE NOT NULL,
    CONSTRAINT fk_rentals_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE rental_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id BIGINT NOT NULL,
    game_copy_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    processed_date DATE,
    rental_price NUMERIC(10, 2) NOT NULL,
    late_fee NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_rental_items_rental
        FOREIGN KEY (rental_id)
        REFERENCES rentals (id),
    CONSTRAINT fk_rental_items_game_copy
        FOREIGN KEY (game_copy_id)
        REFERENCES game_copies (id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_reviews_game
        FOREIGN KEY (game_id)
        REFERENCES games (id),
    CONSTRAINT uk_reviews_user_game UNIQUE (user_id, game_id)
);

CREATE INDEX idx_game_copies_game_status
    ON game_copies (game_id, status);

CREATE INDEX idx_rentals_user
    ON rentals (user_id);

CREATE INDEX idx_rental_items_rental
    ON rental_items (rental_id);

CREATE INDEX idx_rental_items_game_copy
    ON rental_items (game_copy_id);

CREATE INDEX idx_reviews_game
    ON reviews (game_id);
