spring:
  application:
    name: moul-cyber
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:moul_cyber}
    username: ${DB_USERNAME:moul_cyber}
    password: ${DB_PASSWORD:moul_cyber}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:bW91bC1jeWJlci1sb2NhbC1qd3Qtc2VjcmV0LWNoYW5nZS1tZS1iZWZvcmUtcHJvZHVjdGlvbg==}
    expiration: ${JWT_EXPIRATION:1h}
