spring:
  application:
    name: moul-cyber
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:moul_cyber}
    username: ${DB_USERNAME:moul_cyber}
    password: ${DB_PASSWORD:moul_cyber}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
